In [1]:
from neuron import Neuron

In [2]:
inputs = [0.1, 0.4, 0.2]

In [3]:
neuron = Neuron(len(inputs))

In [4]:
neuron.feedforward(inputs)

0.33559509336130805

In [5]:
from layer import Layer

In [6]:
layer = Layer(num_neurons=5, neuron_input_size=3)

In [7]:
layer.feedforward(inputs)

array([0.81266943, 0.73499058, 0.39539231, 0.25776031, 0.19453405])

In [8]:
from neural_network import NeuralNetwork

In [9]:
config = [len(inputs), 10, 11, 15, 1]

In [10]:
neural_network = NeuralNetwork(config)

In [11]:
neural_network.feedforward(inputs)

array([0.50371044])

In [12]:
import utils

In [13]:
utils.draw_neural_network(neural_network)

In [14]:
import numpy as np

In [15]:
X_train = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    
y_train = np.array([
    [0],  # 0 XOR 0 = 0
    [1],  # 0 XOR 1 = 1
    [1],  # 1 XOR 0 = 1
    [0]   # 1 XOR 1 = 0
])

In [47]:
config = [len(X_train[0]), 4, 4, len(y_train[0])]
config

[2, 4, 4, 1]

In [48]:
neural_network = NeuralNetwork(config)

In [49]:
utils.draw_neural_network(neural_network)

In [50]:
neural_network.predict(X_train[0])

array([0.77137246])

In [51]:
neural_network.train(X_train, y_train, epochs=1000, learning_rate=1.0)

Epoch 0, Average Loss: 0.359129
Epoch 10, Average Loss: 0.330617
Epoch 20, Average Loss: 0.315520
Epoch 30, Average Loss: 0.303436
Epoch 40, Average Loss: 0.292592
Epoch 50, Average Loss: 0.277026
Epoch 60, Average Loss: 0.246962
Epoch 70, Average Loss: 0.194844
Epoch 80, Average Loss: 0.134014
Epoch 90, Average Loss: 0.082960
Epoch 100, Average Loss: 0.052338
Epoch 110, Average Loss: 0.035726
Epoch 120, Average Loss: 0.026205
Epoch 130, Average Loss: 0.020300
Epoch 140, Average Loss: 0.016376
Epoch 150, Average Loss: 0.013619
Epoch 160, Average Loss: 0.011596
Epoch 170, Average Loss: 0.010058
Epoch 180, Average Loss: 0.008855
Epoch 190, Average Loss: 0.007892
Epoch 200, Average Loss: 0.007105
Epoch 210, Average Loss: 0.006452
Epoch 220, Average Loss: 0.005902
Epoch 230, Average Loss: 0.005434
Epoch 240, Average Loss: 0.005030
Epoch 250, Average Loss: 0.004679
Epoch 260, Average Loss: 0.004371
Epoch 270, Average Loss: 0.004099
Epoch 280, Average Loss: 0.003857
Epoch 290, Average Loss: 

In [ ]:
for i, x in enumerate(X_train):
    prediction = neural_network.predict(x)
    print(f"Input: {x} | Target: {y_train[i]} | Prediction: {prediction[0]:.4f}")
    
    predictions = []
    for x in X_train:
        pred = neural_network.predict(x)[0]
        predictions.append(1 if pred > 0.5 else 0)
    
    accuracy = np.mean(predictions == y_train.flatten())
    print(f"\nFinal Accuracy: {accuracy * 100:.1f}%")

Input: [0 0] | Target: [0] | Prediction: 0.0274

Final Accuracy: 100.0%
Input: [0 1] | Target: [1] | Prediction: 0.9745

Final Accuracy: 100.0%
Input: [1 0] | Target: [1] | Prediction: 0.9720

Final Accuracy: 100.0%
Input: [1 1] | Target: [0] | Prediction: 0.0226

Final Accuracy: 100.0%
